# Default values for hzero-rule-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-rule-engine
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    # 是否初始化groovy脚本或excel数据
    enable: false
    # 初始化数据库配置
    datasource:
      url: jdbc:mysql://db.hzero.com.cn:3306/hzero_rule_engine?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hres
      password: hres
env:
  open:
    # 是否自动刷新服务权限
    CHOERODON_EUREKA_EVENT_PARSE_PERMISSION: true
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.com.cn:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.com.cn:8010/
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.com.cn:3306/hzero_rule_engine?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hres
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hres
    # Redis host
    SPRING_REDIS_HOST: redis.hzero.com.cn
    # Redis port
    SPRING_REDIS_PORT: 6379
    # Redis DB
    SPRING_REDIS_DATABASE: 1
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 30000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 3000
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
    # 默认 -1 表示永不超时，设置5秒
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    # Redis连接超时时间
    SPRING_REDIS_CONNECT_TIMEOUT: 2000
    # Redis读取超时时间
    SPRING_REDIS_READ_TIMEOUT: 5000
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接
    # 默认值为8，建议设置每个CPU核心一个线程
    SERVER_UNDERTOW_IO_THREADS: 4
    # 每块buffer的空间大小，越小空间被利用越充分
     # 不要设置太大，以免影响其他应用，合适即可
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    # 启用断路器
    FEIGN_CIRCUITBREAKER_ENABLED: true
    # 配置请求GZIP压缩
    FEIGN_COMPRESSION_REQUEST_ENABLED: true
    # 配置压缩数据大小的下限
    FEIGN_COMPRESSION_REQUEST_MIN_REQUEST_SIZE: 2048
    # 连接超时
    FEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT: 2000
    # 读取超时
    FEIGN_CLIENT_CONFIG_DEFAULT_READ_TIMEOUT: 5000
    # 数据库所有者
    HZERO_DB_OWNER: null
    # 数据权限本地缓存过期时间
    HZERO_DATA_PERMISSION_CACHE_EXPIR_TIME: 1s
    # 匹配的资源才会解析JwtToken便于得到UserDetails
    HZERO_RESOURCE_PATTERN: /v1/*,/hres-test/*,/hres-test/v1/*
    # 标签
    SPRING_CLOUD_CONFIG_LABEL: null
    # 是否重试
    SPRING_CLOUD_LB_RETRY_ENABLED: false
    # 重试下一个实例的次数
    SPRING_CLOUD_LB_RETRY_NEXT: 1
    # 重试同一个实例的次数
    SPRING_CLOUD_LB_RETRY_SAME: 0
    # LB 中缓存实例的过期时间
    SPRING_CLOUD_LB_CACHE_TTL: 10s
    # 日志级别
    LOG_LEVEL: info
    SPRING_DATA_MONGODB_URI: mongodb://hzero:hzero@mongo.hzero.com.cn:27017/hres
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8065
  name: hzero-rule-engine
deployment:
  # 管理端口
  managementPort: 8066
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
# 服务治理相关配置
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT
