# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-im
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    # 是否初始化groovy脚本或excel数据
    enable: false
    # 初始化数据库配置
    datasource:
      url: DATASOURCE_CONNECTION
      username: DATASOUCE_USERNAME
      password: DATASOURCE_PASSWORD
env:
  open:
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.com.cn:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.com.cn:8010/
    # Redis host
    SPRING_REDIS_HOST: redis.hzero.com.cn
    # Redis port
    SPRING_REDIS_PORT: 6379
    # Redis DB
    SPRING_REDIS_DATABASE: 8
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 12000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 5000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 2000
    # IO线程数, 它主要执行非阻塞的任务
    SERVER_UNDERTOW_IO_THREADS: 4
    # 阻塞任务线程池
    SERVER_UNDERTOW_WORKER_THREADS: 128
    # 每块buffer的空间大小，越小空间被利用越充分
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 等待连接池分配连接的最大时长（毫秒）
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hzero
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hzero
    # 资源池中最大连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    # 资源池运行最大空闲的连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
    SPRING_REDIS_POOL_MAX_IDLE: 50
    # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
    # 默认 -1 表示永不超时，设置5秒
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    # 数据库所有者模式，例如 SqlServer 下的 dbo/guest
    HZERO_DB_OWNER: null
    # 数据权限本地缓存过期时间
    HZERO_DATA_PERMISSION_CACHE_EXPIR_TIME: 1s
    # 日志级别
    LOG_LEVEL: info
    # 内存限制
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
    # IM基础配置
    HZERO_IM_OAUTH_URL: http://HZERO-OAUTH/oauth/api/user
    #IM ws地址，该地址的映射端口需与tio端口配置保持一致，默认为9876端口
    HZERO_IM_WEBSOCKET_ADDRESS: 192.168.16.150:9876
    # 是否开启智能客服
    HZERO_IM_OPEN_SMART_CUSTOMER: true
    # 是否开启即时通讯
    HZERO_IM_OPEN_INSTANT_MESSAGING: true
    # mongodb配置
    SPRING_MONGO_HOSTS: mongo.hzero.com.cn
    SPRING_MONGO_USERNAME: hzero
    SPRING_MONGO_PASSWORD: hzero
    SPRING_MONGO_PORT: 27017
    SPRING_MONGO_DATABASE: hims
    # 资源路径
    HZERO_RESOURCE_PATTERN: /v1/*,/hims/v1/*
    # IM文件存储桶名
    HZERO_IM_BUCKET_NAME: hims
    # 标签
    SPRING_CLOUD_CONFIG_LABEL: null
    # TIO websocket连接端口
    TIO_WEBSOCKET_PORT: 9876
    # 心跳时间
    TIO_WEBSOCKET_HEARTBEAT: 60000
    # 微信企业号模板编码
    HZERO_IM_WECHAT_CODE: TEST
    # 微信企业号应用Id，若不加该配置则会获取微信企业号配置下的默认应用Id
    HZERO_IM_WECHAT_AGENT: null
    # Ribbon从DiscoveryClient同步Server的间隔时间，默认30秒
    RIBBON_SERVER_LIST_REFRESH_INTERVAL: 10000
    # 续约间隔时间，默认30秒
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    # 实例故障摘除时间，默认90秒，实际是90*2=180秒，配置45就是90秒
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    # 执行命令线程池的核心线程数，也是命令执行的最大并发量，默认10
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 128
    # 最大执行线程数
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 256
    # Redis连接超时时间
    SPRING_REDIS_CONNECT_TIMEOUT: 2000
    # Redis读取超时时间
    SPRING_REDIS_READ_TIMEOUT: 5000
    # 启用断路器
    FEIGN_CIRCUITBREAKER_ENABLED: true
    # 配置请求GZIP压缩
    FEIGN_COMPRESSION_REQUEST_ENABLED: true
    # 配置压缩数据大小的下限
    FEIGN_COMPRESSION_REQUEST_MIN_REQUEST_SIZE: 2048
    # 连接超时
    FEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT: 2000
    # 读取超时
    FEIGN_CLIENT_CONFIG_DEFAULT_READ_TIMEOUT: 5000
    # 是否重试
    SPRING_CLOUD_LB_RETRY_ENABLED: false
    # 重试下一个实例的次数
    SPRING_CLOUD_LB_RETRY_NEXT: 1
    # 重试同一个实例的次数
    SPRING_CLOUD_LB_RETRY_SAME: 0
    # LB 中缓存实例的过期时间
    SPRING_CLOUD_LB_CACHE_TTL: 10s
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8025
  name: hzero-im
deployment:
  managementPort: 8026
resources:
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
