# Default values for hzero-oauth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-oauth
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    # 是否初始化groovy脚本或excel数据
    enable: false
    # 初始化数据库配置
    datasource:
      url: jdbc:mysql://db.hzero.com.cn:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    # 认证服务器 自定义资源匹配器
    HZERO_OAUTH_CUSTOM_RESOURCE_MATCHER: false
    # 验证 client 时不检查 client 的一致性
    HZERO_OAUTH_NOT_CHECK_CLIENT_EQUALS: false
    # 移动设备ID参数
    HZERO_OAUTH_DEVICE_ID_PARAMETER: device_id
    # 登录设备来源参数
    HZERO_OAUTH_SOURCE_TYPE_PARAMETER: source_type
    # 移动端开启图形验证码校验，默认不开启
    HZERO_OAUTH_ENABLE_APP_CAPTCHA: false
    # 始终开启图形验证码校验，默认否
    HZERO_OAUTH_ENABLE_ALWAYS_CAPTCHA: false
    # client_credentials 模式是否返回 refresh_token
    HZERO_OAUTH_CREDENTIALS_ALLOW_REFRESH: false
    # 是否检查redirect_uri的一致性
    HZERO_OAUTH_CHECK_REDIRECT_URI: true
    # 允许使用的登录名，默认有 用户名、邮箱、手机号
    HZERO_OAUTH_LOGIN_SUPPORT_FIELDS: username,email,phone
    # 前端默认模板
    HZERO_OAUTH_LOGIN_DEFAULT_TEMPLATE: slide
    # 默认登录成功跳转地址
    HZERO_OAUTH_LOGIN_SUCCESS_URL: http://localhost:8000/workplace
    # 密码防重放缓存过期时间，单位(天)
    HZERO_OAUTH_LOGIN_PASS_REPLAY_EXPIRE: 30
    # 默认客户端
    HZERO_OAUTH_LOGIN_DEFAULT_CLIENT_ID: hzero-front-dev
    # 登录密码是否加密传输
    HZERO_OAUTH_LOGIN_PASSWORD_ENCRYPT: true
    # 登录账号是否加密传输
    HZERO_OAUTH_LOGIN_ACCOUNT_ENCRYPT: false
    # 是否开启登入系统时选择租户与角色，默认开启
    HZERO_OAUTH_LOGIN_ENABLE_SUTAR: true
    # oauth服务基础地址
    HZERO_OAUTH_BASE_URL: http://dev.hzero.com.cn:8080/oauth
    # 是否启用兼容模式，兼容老版本跳转地址
    HZERO_OAUTH_SSO_ENABLE_COMPATIBILITY_MODE: false
    # 数据库所有者模式，例如 SqlServer 下的 dbo/guest
    HZERO_DB_OWNER: null
    # 数据权限本地缓存过期时间
    HZERO_DATA_PERMISSION_CACHE_EXPIR_TIME: 1s
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.com.cn:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.com.cn:8010/
    # 是否重试
    SPRING_CLOUD_LB_RETRY_ENABLED: false
    # 重试下一个实例的次数
    SPRING_CLOUD_LB_RETRY_NEXT: 1
    # 重试同一个实例的次数
    SPRING_CLOUD_LB_RETRY_SAME: 0
    # LB 中缓存实例的过期时间
    SPRING_CLOUD_LB_CACHE_TTL: 10s
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.com.cn:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hzero
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hzero
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 等待连接池分配连接的最大时长（毫秒）
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    # Redis host
    SPRING_REDIS_HOST: redis.hzero.com.cn
    # Redis Port
    SPRING_REDIS_PORT: 6379
    # Redis DB
    SPRING_REDIS_DATABASE: 3
    # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
    # 默认 -1 表示永不超时，设置5秒
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    # 资源池中最大连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    # 资源池运行最大空闲的连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
    SPRING_REDIS_POOL_MAX_IDLE: 50
    # Redis连接超时时间
    SPRING_REDIS_CONNECT_TIMEOUT: 2000
    # Redis读取超时时间
    SPRING_REDIS_READ_TIMEOUT: 5000
    # 启用断路器
    FEIGN_CIRCUITBREAKER_ENABLED: true
    # 配置请求GZIP压缩
    FEIGN_COMPRESSION_REQUEST_ENABLED: true
    # 配置压缩数据大小的下限
    FEIGN_COMPRESSION_REQUEST_MIN_REQUEST_SIZE: 2048
    # 连接超时
    FEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT: 2000
    # 读取超时
    FEIGN_CLIENT_CONFIG_DEFAULT_READ_TIMEOUT: 5000
    # hystrix熔断时间，12秒，需大于feign/ribbon的超时时间
    # 默认 1000 毫秒，最高设置 2000足矣。如果超时，首先看能不能优化接口相关业务、SQL查询等，不要盲目加大超时时间，否则会导致线程堆积过多，hystrix 线程池卡死，最终服务不可用。
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 12000
    # 执行命令线程池的核心线程数，也是命令执行的最大并发量，默认10
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 128
    # 最大执行线程数
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 256
    # Ribbon从DiscoveryClient同步Server的间隔时间，默认30秒
    RIBBON_SERVER_LIST_REFRESH_INTERVAL: 10000
    # 客户端读取超时时间，超时时间要小于Hystrix的超时时间，否则重试机制就无意义了
    RIBBON_READ_TIMEOUT: 5000
    # 客户端连接超时时间
    RIBBON_CONNECT_TIMEOUT: 2000
    # 续约间隔时间，默认30秒
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    # 实例故障摘除时间，默认90秒，实际是90*2=180秒，配置45就是90秒
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    # session 失效时间设置短一点，登录后让 Session 自动失效
    SERVER_SERVLET_SESSION_TIMEOUT: 120
    # IO线程数, 它主要执行非阻塞的任务
    SERVER_UNDERTOW_IO_THREADS: 4
    # 阻塞任务线程池
    SERVER_UNDERTOW_WORKER_THREADS: 128
    # 每块buffer的空间大小，越小空间被利用越充分
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    #
    SESSION_COOKIE_PATH: /oauth
    # 生效配置
    SPRING_PROFILES_ACTIVE: default
    # 是否启用 Root 用户功能
    HZERO_USER_ENABLE_ROOT: false
    # 标签
    SPRING_CLOUD_CONFIG_LABEL: null
    # 日志级别
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:
service:
  enabled: false
  type: ClusterIP
  port: 8020
  name: hzero-oauth
deployment:
  # 管理端口
  managementPort: 8021
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
